### ISSUE TITLE
Some css issues

### ISSUE THREAD

**Issue by KoukeFoxes** [RikisuT/Youtube-Fluent-Theme#1]
Original YouTube
![image](https://user-images.githubusercontent.com/65907692/182436017-12b380aa-01ca-4eda-831f-5d3ac0765d96.png)

Whit Fluent Theme
![image](https://user-images.githubusercontent.com/65907692/182436102-abc44f29-c1d4-4837-8615-15c0750f524c.png)

There some mistake on the website like top bar width or left-side menu is gone with your 2 css file.
And there 2 issue on Stylus
![image](https://user-images.githubusercontent.com/65907692/182436461-d2c44b1a-18ac-4262-b6e1-b3f3a7b79a5e.png)

**Comment by RikisuT** [comment]
Fixed them
