### ISSUE TITLE
Not Working on UserStyles Website

### ISSUE THREAD

**Issue by ItsEpicBeast** [RikisuT/Youtube-Fluent-Theme#12]
I am getting this error when trying to upload the CSS code using https://userstyles.org/ and other errors that involve ```--yt```
![Screenshot 2024-05-23 010256](https://github.com/RikisuT/Youtube-Fluent-Theme/assets/52136474/9c7da87b-cc1f-41d8-a4ea-416131349178)

**Comment by RikisuT** [comment]
It looks like Userstyles doesn't support changing the site's variable's values.
You will have to manually go and fine wherever the variable was used and type the CSS code to overwrite it with the variable's value
