### ISSUE TITLE
Videos cover disappear when the mouse is hover on  it.

### ISSUE THREAD

**Issue by luoweijun618** [RikisuT/Youtube-Fluent-Theme#9]
Im using the "personal-backup" css form the 5.0.0 because it's the newest i can found.
Here's the issue looks like:
![image](https://github.com/RikisuT/Youtube-Fluent-Theme/assets/114051548/138fa954-4229-46f2-b2d1-fbb3eb0ad368)
Thanks.

**Comment by luoweijun618** [comment]
And if I change to "theme-with-caption-window-blur" css, the description would dissapear.
Here's the issue looks like:
![image](https://github.com/RikisuT/Youtube-Fluent-Theme/assets/114051548/0390978f-bfd7-4914-8a9b-92fc7c768a6f)

**Comment by RikisuT** [comment]
Should be fixed now
I made changes to the theme with inline preview on
I had forgotten to check with it off
